# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Tests

on: [push, pull_request]
  # push:
  #   branches-ignore: [ master ]
  # pull_request:
  #   branches-ignore: [ master ]

jobs:
  test:

    name: ${{ matrix.test-script }} (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      max-parallel: 1
      matrix:
        # 10.x breaks Discord.MessageEmbed.fields: Array.prototype.flat() >= 11.0 only
        # 14.x breaks Keyv !
        node-version: [ 12.x, 13.x ]
        test-script: ["roll", "client"]

    steps:
      - name: 📡 Checkout
        uses: actions/checkout@v2

      - name: ⚙ Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: ☕ Install Dependencies
        run: npm ci

      - name: 🔧 Tests
        run: npm run test-${{ matrix.test-script }}
        env:
          # DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TOKEN: ${{ secrets.DISCORD_BETA_BOT_TOKEN }}
