# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: TESTS (Node.js CI)

on:
  push:
    branches-ignore: [ master ]
  pull_request:
    branches-ignore: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # 14.x breaks Keyv !
        node-version: [ 10.x, 12.x ]

    steps:
    - name: 📡 Checkout
      uses: actions/checkout@v2

    - name: ⚙ Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: ☕ Install Dependencies
      run: npm ci

    - name: 🔧 Tests
      run: npm test
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        TOKEN: ${{ secrets.DISCORD_BETA_BOT_TOKEN }}